### ISSUE TITLE
Type stability around this package

### ISSUE THREAD

**Issue by ChenNingCong** [My-laniaKeA/DashSVD.jl#6]
1. In EigSVD.jl, you should use `eigen(LinearAlgebra.Hermitian(V))` to decompose a herimitan matrix. Otherwise the type is unstable (returns a union).
2. In DashSVD.jl,
https://github.com/My-laniaKeA/DashSVD.jl/blob/48a576db72da43395cda5193d539af4e83fa2c9f/src/DashSVD.jl#LL78C1-L80C16
```
		alpha = 0
		sk_now = 0
		sk = zeros(l)
```
alpha should be initialized with a floating number, because it;s reasssigned later with `alpha = (alpha + S[1])/2`, a floating number. This is type unstable. `sk_now = 0` should be removed, because it's useless (sk_now is only defined and used in the following loop body).

3. Please throw error directly instead of return nothing if the input is troublesome.
```
if k > min(m, n)
		@warn "Rank k must be no more than min(m, n) !"
		return
	end
```
This will cause problem when other people use your code (it returns union).

These errors are found by [SimpleTypeChecker](https://github.com/ChenNingCong/SimpleTypeChecker/tree/main), a fortran-style static type checker for Julia.

**Comment by My-laniaKeA** [comment]
Thank you for bringing this issue to our attention. I am happy to inform you that we have fixed the problem and the fix will be included in our next release.
